import type { Brand } from './types';

export interface WordCard {
	id: Brand<'wordCard'>;
	words: string[];
}

export interface QuestionCard {
	id: Brand<'questionCard'>;
	title: string;
	question: string;
}

export const words = makeWordCards([
	['Marble', 'Parasol', 'Caterpillar', 'Chili', 'Corkscrew', 'Chalkboard'],
	['Cactus', 'Igloo', 'Popcorn', 'Penguin', 'Headphones', 'Tiger'],
	['Oven', 'Quill', 'Metronome', 'Cheese', 'Wand', 'Duck'],
	['Monocle', 'Feather', 'Book', 'Crayon', 'Sled', 'Seahorse'],
	['Grill', 'Stove', 'Printer', 'Egg', 'Leash', 'Thermos'],
	['Trophy', 'Cougar', 'Fox', 'Wallet', 'Peacock', 'Ruby'],
	['Camera', 'Fork', 'Whale', 'Match', 'Clock', 'Mirror'],
	['Pig', 'Pillow', 'Submarine', 'Iceberg', 'Skyscraper', 'Hat'],
	['Crown', 'Balloon', 'Fence', 'Stapler', 'Hammer', 'Helmet'],
	['Hydrant', 'Pencil', 'Barn', 'Stamp', 'Platypus', 'Ruler'],
	['Saw', 'Cherry', 'Zombie', 'Vulture', 'Knife', 'Rat'],
	['Hammock', 'Box', 'Cake', 'Harp', 'Dinosaur', 'Guitar'],
	['Chain', 'Honey', 'Tent', 'Towel', 'Peanut', 'Pizza'],
	['Wrench', 'Anchor', 'Ladder', 'Skull', 'Whistle', 'Violin'],
	['Magazine', 'Sun', 'Horse', 'Cloud', 'Broom', 'Starfish'],
	['Radio', 'Chocolate', 'Map', 'Flower', 'Television', 'Dictionary'],
	['Bed', 'Ring', 'Toilet', 'Globe', 'Door', 'Sock'],
	['Ladle', 'Statue', 'Cat', 'Sink', 'Sausage', 'Deer'],
	['Bread', 'Uniform', 'Chopstick', 'Pitchfork', 'Wheelchair', 'Jellyfish'],
	['Pineapple', 'Worm', 'Mouse', 'Coconut', 'Unicorn', 'Compass'],
	['Cloak', 'Gong', 'Mosquito', 'Coffee', 'Bicycle', 'Shower'],
	['Sandal', 'Crow', 'Battery', 'Slipper', 'Basketball', 'Snowball'],
	['Ostrich', 'Panda', 'Receipt', 'Slide', 'Skeleton', 'Bridge'],
	['Rope', 'Car', 'Apron', 'Snorkel', 'Icicle', 'Shirt'],
	['Spatula', 'Giraffe', 'Satellite', 'Sword', 'Heart', 'Castle'],
	['Seesaw', 'Dragon', 'Jackhammer', 'Zipper', 'Sand', 'Squid'],
	['Tissue', 'Microphone', 'Acorn', 'Lunchbox', 'Butterfly', 'Fossil'],
	['Computer', 'Drum', 'Suitcase', 'Blanket', 'Sunflower', 'Sandwich'],
	['Shield', 'Diamond', 'Comb', 'Turtle', 'Tire', 'Brick'],
	['Boot', 'Roof', 'Necklace', 'Truck', 'Windmill', 'Lamp'],
	['Brain', 'Fireplace', 'Lawnmower', 'Laptop', 'Chair', 'Gate'],
	['Beetle', 'Ramen', 'Catapult', 'Watermelon', 'Flashlight', 'Dolphin'],
	['Microwave', 'Podium', 'Wine', 'Apple', 'Pancake', 'Rose'],
	['Bear', 'Safe', 'Planet', 'Train', 'Spoon', 'Newspaper'],
	['Butter', 'Shoe', 'Screwdriver', 'Camel', 'Tea', 'Steak'],
	['Elevator', 'Pyramid', 'Stilt', 'Octopus', 'Staff', 'Rainbow'],
	['Shovel', 'Magnet', 'Scissors', 'Vacuum', 'Pen', 'Eraser'],
	['Pigeon', 'Ship', 'Soap', 'Telescope', 'Toothpick', 'Window'],
	['Earring', 'Mushroom', 'Backpack', 'Crystal', 'Toothpaste', 'Jam'],
	['Doll', 'House', 'Crane', 'Burrito', 'Snail', 'Skateboard'],
	['Key', 'Eagle', 'Mermaid', 'Umbrella', 'Painting', 'Goldfish'],
	['Helicopter', 'Pumpkin', 'Tree', 'Ant', 'Toothbrush', 'Missile'],
	['Stump', 'Binoculars', 'Ski', 'Gold', 'Mailbox', 'Envelope'],
	['Parrot', 'Sponge', 'Needle', 'Basket', 'Mask', 'Chalk'],
	['Dog', 'Toast', 'Mountain', 'Tape', 'Jar', 'Perfume'],
	['Milk', 'Vacuum', 'Buoy', 'Candle', 'Cabbage', 'Pie'],
	['Toaster', 'Chainsaw', 'Tractor', 'Blowfish', 'Mustard', 'Ambulance'],
	['Organ', 'Crowbar', 'Robot', 'Kite', 'Flag', 'Birdhouse'],
	['Lightbulb', 'Pearl', 'Puzzle', 'Baseball', 'Bell', 'Elephant'],
	['Sidewalk', 'Cigar', 'Keyboard', 'Piano', 'Zebra', 'Steamroller'],
	['Fish', 'Sugar', 'Moon', 'Bowl', 'Treadmill', 'Snowshoe'],
	['Ticket', 'Coin', 'Scorpion', 'Sunglasses', 'Bottle', 'Blender'],
] satisfies string[][]);

export const questions = makeQuestionCards([
	['COST', 'What does it cost about the same as?'],
	['SIZE', "What's it about the same size as?"],
	['WEIGHT', 'What does it weigh about the same as?'],
	['DANGER', "What's about as dangerous as it?"],
	['ANIMAL', 'If it were an animal, what animal would it be?'],
	['INSTRUMENT', 'If it were a musical instrument, what would it be?'],
	['FOOD', 'If it were a food, what food would it be?'],
	['FAVORITE FOOD', 'If it had a favorite food, what would it be?'],
	['ACADEMIC', 'What academic field studies it?'],
	['HISTORICAL', "Who's a historical figure that had or used it?"],
	['CELEBRITY', "Who's a celebrity that has or uses it?"],
	['CHARACTER', "Who's a fictional character that has or uses it?"],
	["HOW IT'S MADE", 'How is it made?'],
	['TRANSPORT', 'How is it transported?'],
	['WEAPON', 'How would you use it as a weapon?'],
	['CONCEPT', 'What abstract concept is it associated with?'],
	['ACCIDENT', 'What accident or injury would it cause?'],
	['ADJECTIVE', 'What adjective best describes it?'],
	['GREEK GOD', 'What ancient Greek or Roman god is it most associated with?'],
	['CATEGORY', 'What category of objects does it fall under?'],
	['COLOR', 'What color is it?'],
	['CONTAINER', 'What container would you keep it in?'],
	['NEED', "What's something you need in order to use it?"],
	['SMELL', 'What does it smell like?'],
	['TASTE', 'What does it taste like?'],
	['SCIENCE', 'What field of science studies it?'],
	['GENRE', 'What genre of movie or book is most likely to feature it?'],
	['USE', 'What is it used for?'],
	['CAUSE', 'What causes you to use it?'],
	['WHO USES IT', 'What kind of people have or use it?'],
	['STORE', 'What kind of store are you most likely to find it in?'],
	['MATERIAL', 'What material is it made of?'],
	['NICKNAME', "What's a nickname for it?"],
	['SOUND EFFECT', "What onomatopoeia does it make ('boom', 'meow', etc.)?"],
	['BODY PART', 'What part of the body do you use it with?'],
	['POWER', 'What powers it?'],
	['PROFESSION', 'What profession works with it?'],
	['MEDIA', "What's a book, movie, or TV show that it appears in?"],
	['BRAND', "What's a common brand of it?"],
	['VARIETY', "What's a variety it comes in?"],
	['LIES', 'What has NOTHING to do with it, just to confuse the other team?'],
	['INSIDE', "What's inside it?"],
	['SIMILAR', "What's something that is like it?"],
	['MAKE', "What's something you can make using it?"],
	['FAVORITE', "What's your favorite type of it?"],
	['WHERE USED', 'Where do you use it?'],
	['DISCARD', 'Where does it go when it dies, breaks, or is no longer useful?'],
	['HOUSE', 'Where in a house would you find it?'],
	['STORAGE', 'Where is it stored?'],
	['WHERE', 'Where would you find it?'],
	['BUY', 'Where would you buy or obtain one?'],
	['WHO MAKES', 'Who or what makes it?'],
	['AGE', 'What age group likes it the most?'],
	['FIGHT', 'What causes people to fight over it?'],
	['CITY', 'What city is it most associated with?'],
	['REGION', 'What continent or region would you find the most of these in?'],
	['CLOTHES', "What's something you wear when using it?"],
	['STORY', 'What fairy tale or nursery rhyme does it most belong in?'],
	['ASSOCIATION', "What's the first word that pops into your head about it?"],
	['SUPERHERO', 'What superhero is it most associated with?'],
	['DISLIKE', 'Who dislikes it?'],
	['SCHOOL', 'What subject in school teaches about it?'],
	['NEAREST', 'Where is the nearest one?'],
	['SHAPE', "What's a geometric shape that it includes?"],
	['LIFETIME', 'At what point in your life is it most useful?'],
	['FEELING', 'How do you feel after using it?'],
	['YOUR OPINION', 'How do you personally feel about it?'],
	['GIFT', 'How do you feel when someone gifts it to you?'],
	['AFFECT', 'How does it affect the things around it?'],
	['LONGEVITY', 'How long will it last if left alone?'],
	['HILL', 'How would it react to being pushed down a hill?'],
	['CHANGE', 'What changes it?'],
	['COUNTRY', 'What country is it most associated with?'],
	['HALF', 'What do you do with it if you only have half of it?'],
	['TEXTURE', 'What does it feel like when you touch it?'],
	['HABITAT', 'What habitat would you be most likely to find it in?'],
	['WATER', 'What happens if you put it underwater?'],
	['RAIN', "What happens to it when it's left out in the rain?"],
	['HOLIDAY', 'What holiday is it most associated with?'],
	['NOISE', 'What kind of noise does it make when used?'],
	['NOT THIS MATERIAL', 'What material is it NOT made of?'],
	['DROPPED', 'What noise does it make when dropped?'],
	['PARTY', 'What party theme would fit it best?'],
	['SUPER POWER', 'What superpower would it want?'],
	['TIME', 'What time of day is it used?'],
	['BURY', 'What would happen if it was buried for a year?'],
	['DESTROY', 'What would you use to destroy it?'],
	['GAME', "What's a game that it appears in?"],
	['INCORRECT', "What's an incorrect way to use it?"],
	['OPPOSITE', "What's its opposite?"],
	['2ND MATERIAL', "What's the secondary material it's made of?"],
	['LIKE', 'Who at this table likes it the most?'],
	['LIFT', 'Who or what can lift it?'],
	['FREQUENCY', 'How frequently do you use it?'],
	['MOVES', 'How does it move?'],
	['PROBLEM', 'What problem does it solve?'],
	['HOLD', 'How do you hold onto it?'],
	['CEREMONY', 'What ceremony would it appear in?'],
	['RESTAURANT', 'What kind of restaurant would be most likely to serve it?'],
	['TOURIST', 'What tourist destination would you most likely find it at?'],
	['EAT', 'What would happen if you ate it?'],
	['MOOD', 'What mood does it cause?'],
] satisfies Array<[title: string, question: string]>);

export const board = {
	turns: 8,
	sun: { hints: [3, 5, 6] },
	moon: { hints: [2, 4, 5] },
};

function makeWordCards(cards: string[][]): WordCard[] {
	return cards.map((cardWords, index) => ({
		id: String(index + 1) as Brand<'wordCard'>,
		words: cardWords.map(word => word.toUpperCase()),
	}));
}

function makeQuestionCards(cards: Array<[title: string, question: string]>): QuestionCard[] {
	return cards.map(([title, question], index) => ({
		id: String(index + 1) as Brand<'questionCard'>,
		title,
		question,
	}));
}
